# Generated by Django 2.1.2 on 2018-11-05 17:10

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='circulars.Category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('product_slug', models.SlugField(blank=True, editable=False, max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('product_image', models.ImageField(upload_to='media/images/products/')),
                ('product_desc', models.TextField(blank=True)),
                ('category', models.ManyToManyField(blank=True, to='circulars.Category')),
            ],
            options={
                'verbose_name_plural': 'Coupons',
                'ordering': ['product'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='circulars.Location')),
            ],
            options={
                'verbose_name_plural': 'Locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=150)),
                ('logo', models.ImageField(upload_to='media/images/stores/')),
                ('desc', models.TextField(blank=True)),
                ('location', models.ManyToManyField(to='circulars.Location')),
            ],
            options={
                'verbose_name_plural': 'Stores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=75)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=75)),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'ordering': ['tag'],
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circulars.Store'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='tags',
            field=models.ManyToManyField(blank=True, to='circulars.Tag'),
        ),
    ]
