# Generated by Django 2.1.2 on 2019-01-20 16:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='circulars.Category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=datetime.date.today, editable=False)),
                ('date_expired', models.DateField(default=datetime.date.today)),
            ],
            options={
                'verbose_name_plural': 'Coupons',
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='Flyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_created', models.DateField(default=datetime.date.today, editable=False)),
                ('date_expired', models.DateField(default=datetime.date.today)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255)),
                ('image', models.ImageField(upload_to='media/images/flyers')),
                ('desc', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Flyers',
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='circulars.Location')),
            ],
            options={
                'verbose_name_plural': 'Locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255)),
                ('r_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Regular Price')),
                ('s_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Sale Price')),
                ('image', models.ImageField(upload_to='media/images/products')),
                ('desc', models.TextField(blank=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='circulars.Category')),
                ('coupon', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='circulars.Coupon')),
                ('flyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='circulars.Flyer')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=150)),
                ('logo', models.ImageField(upload_to='media/images/stores/')),
                ('desc', models.TextField(blank=True)),
                ('location', models.ManyToManyField(related_name='stores', to='circulars.Location')),
            ],
            options={
                'verbose_name_plural': 'Stores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=75)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=75)),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'ordering': ['tag'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='circulars.Tag'),
        ),
        migrations.AddField(
            model_name='flyer',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flyers', to='circulars.Store'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='circulars.Store'),
        ),
    ]
