# Generated by Django 2.1.2 on 2018-11-08 17:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circulars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('c_type', models.CharField(choices=[('flyer', 'Flyer'), ('coupon', 'Coupon')], default='coupon', max_length=12)),
                ('date_created', models.DateField(default=datetime.date.today, editable=False)),
                ('date_expired', models.DateField(default=datetime.date.today)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255)),
                ('image', models.ImageField(upload_to='media/images/circulars')),
                ('desc', models.TextField(blank=True)),
                ('category', models.ManyToManyField(blank=True, to='circulars.Category')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circulars.Store')),
                ('tags', models.ManyToManyField(blank=True, to='circulars.Tag')),
            ],
            options={
                'verbose_name_plural': 'circulars',
                'ordering': ['title'],
            },
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='category',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='store',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
