# Generated by Django 2.1.2 on 2018-11-09 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circulars', '0002_auto_20181108_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255)),
                ('r_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('s_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('image', models.ImageField(upload_to='media/images/products')),
                ('desc', models.TextField(blank=True)),
                ('categories', models.ManyToManyField(blank=True, to='circulars.Category')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='circular',
            name='category',
        ),
        migrations.RemoveField(
            model_name='circular',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='circular',
            name='tags',
        ),
        migrations.AlterField(
            model_name='circular',
            name='c_type',
            field=models.CharField(choices=[('flyer', 'Flyer'), ('coupon', 'Coupon')], default='coupon', max_length=12, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='circular',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circulars', to='circulars.Store'),
        ),
        migrations.AddField(
            model_name='product',
            name='circular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='circulars.Circular'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='circulars.Tag'),
        ),
    ]
