# Generated by Django 2.1.2 on 2018-11-10 11:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circulars', '0003_auto_20181109_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=datetime.date.today, editable=False)),
                ('date_expired', models.DateField(default=datetime.date.today)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='circulars.Store')),
            ],
            options={
                'verbose_name_plural': 'Coupons',
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='Flyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_created', models.DateField(default=datetime.date.today, editable=False)),
                ('date_expired', models.DateField(default=datetime.date.today)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255)),
                ('image', models.ImageField(upload_to='media/images/flyers')),
                ('desc', models.TextField(blank=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flyers', to='circulars.Store')),
            ],
            options={
                'verbose_name_plural': 'Flyers',
                'ordering': ['date_created'],
            },
        ),
        migrations.RemoveField(
            model_name='circular',
            name='store',
        ),
        migrations.RemoveField(
            model_name='product',
            name='circular',
        ),
        migrations.AlterField(
            model_name='product',
            name='r_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Regular Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='s_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Sale Price'),
        ),
        migrations.DeleteModel(
            name='Circular',
        ),
        migrations.AddField(
            model_name='product',
            name='coupon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='circulars.Coupon'),
        ),
        migrations.AddField(
            model_name='product',
            name='flyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='circulars.Flyer'),
        ),
    ]
