# Generated by Django 2.1.2 on 2019-01-20 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circulars', '0004_auto_20181110_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='circulars.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='coupon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='circulars.Coupon'),
        ),
        migrations.AlterField(
            model_name='product',
            name='r_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Regular Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='s_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Sale Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='circulars.Tag'),
        ),
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.ManyToManyField(related_name='stores', to='circulars.Location'),
        ),
    ]
