# Generated by Django 2.1.2 on 2018-10-16 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=75, unique=True)),
                ('area_slug', models.SlugField(blank=True, editable=False, max_length=75)),
            ],
            options={
                'verbose_name_plural': 'Areas',
                'ordering': ['area'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=75)),
                ('city_code', models.CharField(max_length=75, unique=True)),
                ('city_slug', models.SlugField(blank=True, editable=False, max_length=75)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['city'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=75, unique=True)),
                ('country_slug', models.SlugField(blank=True, editable=False, max_length=75)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['country'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('product_slug', models.SlugField(blank=True, editable=False, max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('product_image', models.ImageField(upload_to='media/images/products/')),
                ('product_desc', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Coupons',
                'ordering': ['product'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=75, unique=True)),
                ('store_slug', models.SlugField(blank=True, editable=False, max_length=75)),
                ('store_logo', models.ImageField(upload_to='media/images/stores/')),
                ('store_info', models.TextField(blank=True)),
                ('area', models.ManyToManyField(to='flyers.Area')),
                ('city', models.ManyToManyField(to='flyers.City')),
            ],
            options={
                'verbose_name_plural': 'Stores',
                'ordering': ['store'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=75)),
                ('tag_slug', models.SlugField(blank=True, editable=False, max_length=75)),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'ordering': ['tag'],
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flyers.Store'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='tags',
            field=models.ManyToManyField(blank=True, to='flyers.Tag'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flyers.Country'),
        ),
        migrations.AddField(
            model_name='area',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flyers.City'),
        ),
    ]
