# Generated by Django 2.1.2 on 2018-10-21 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flyers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='city',
        ),
        migrations.RemoveField(
            model_name='city',
            name='city_code',
        ),
        migrations.RemoveField(
            model_name='store',
            name='area',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
