# Generated by Django 2.1.2 on 2018-10-10 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flyers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['area'], 'verbose_name_plural': 'Areas'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['city'], 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['country'], 'verbose_name_plural': 'Countries'},
        ),
    ]
