# Generated by Django 2.1.2 on 2018-10-21 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flyers', '0002_auto_20181021_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=100)),
                ('cat_slug', models.SlugField(blank=True, editable=False, max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flyers.Category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['category'],
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='category',
            field=models.ManyToManyField(blank=True, to='flyers.Category'),
        ),
    ]
